from faker import Faker
import mysql.connector
import random
import csv
import ast


db = mysql.connector.connect(host="localhost",user="khurana",passwd="ishika321",database="skincare_suggestion")

mycursor = db.cursor()

fake = Faker("en_IN") #getting indian output by faker

'''def table1():
	mycursor.execute("""
	CREATE TABLE UserInfo (
	    User_id INT AUTO_INCREMENT PRIMARY KEY,
	    User_name VARCHAR(100) NOT NULL UNIQUE UNIQUE,
	    name VARCHAR(100) NOT NULL,
	    Email VARCHAR(255) NOT NULL UNIQUE,
	    password VARCHAR(100) NOT NULL,
	    Phone_number VARCHAR(20),
	    created_at DATETIME,
	    gender VARCHAR(50),
	    age INT
	)
	""")

# def get_existing_ids(column_name,table_name):
# 	query = f"SELECT {column_name} FROM {table_name}"
# 	mycursor.execute(query)
# 	results = mycursor.fetchall()
# 	return [row[0] for row in results]

def get_existing_ids(column_name,table_name):
	query = f"SELECT {column_name} FROM {table_name}"
	mycursor.execute(query)
	results = mycursor.fetchall()
	return [row[0] for row in results]

def my_user_entry(n):
	data=[]
	for _ in range(1,n+1): #by a loop we are getting as many entries as user wants
		User_name = fake.user_name()
		email = fake.email()
		password = fake.password()
		Phone_number = fake.phone_number()
		created_at = fake.date_time_this_year()
		gender = fake.random_element(['Male','Female'])
		age = fake.random_int(min=18,max=65)
		data.append((User_name,email,password,Phone_number,created_at,gender,age))
		
	mycursor.execute("ALTER TABLE UserInfo AUTO_INCREMENT=1")
	#auto increment is started from 1 to improve accuracy of data
	
	mycursor.executemany(
		"INSERT INTO UserInfo (User_name,email,password,Phone_number,created_at,gender,age) VALUES (%s,%s,%s,%s,%s,%s,%s)",data)
			#data is generated by faker and entered in the table
	db.commit()
	

mycursor.execute("CREATE TABLE SkinInfo (skin_id INT AUTO_INCREMENT PRIMARY KEY,skin_type VARCHAR(100),concern VARCHAR(100),skin_goal VARCHAR(100) ,recommendation VARCHAR(500),to_avoid VARCHAR(500))")

#mycursor.execute("ALTER TABLE SkinInfo AUTO_INCREMENT=1")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, skin_goal, recommendation, to_avoid) VALUES

-- ================= OILY =================
('Oily','Acne','Glowing skin','Niacinamide, Green Tea, Zinc PCA','Coconut Oil, Mineral Oil'),
('Oily','Acne','Reduce acne','Salicylic Acid, Niacinamide, Clay','Heavy Oils, Lanolin'),
('Oily','Acne','Even skin tone','Azelaic Acid, Retinol, Alpha Arbutin','Harsh Acids, Fragrance'),
('Oily','Acne','Hydration','Aloe Vera, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

('Oily','Large Pores','Glowing skin','Niacinamide, Retinol, Clay Mask','Heavy Oils, Petrolatum'),
('Oily','Large Pores','Reduce acne','Salicylic Acid, Zinc PCA, Clay','Coconut Oil, Lanolin'),
('Oily','Large Pores','Even skin tone','Retinol, Niacinamide, Lactic Acid','Harsh Scrubs, Fragrance'),
('Oily','Large Pores','Hydration','Green Tea, Aloe Vera, Panthenol','Alcohol, Essential Oils'),

('Oily','Oil Control','Glowing skin','Niacinamide, Green Tea, Squalane','Heavy Creams, Mineral Oil'),
('Oily','Oil Control','Reduce acne','Zinc PCA, Salicylic Acid, Niacinamide','Coconut Oil, Lanolin'),
('Oily','Oil Control','Even skin tone','Retinol, Azelaic Acid, Niacinamide','Harsh Acids, Fragrance'),
('Oily','Oil Control','Hydration','Aloe Vera, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

('Oily','Uneven Texture','Glowing skin','Lactic Acid, Retinol, Niacinamide','Harsh Scrubs, Alcohol'),
('Oily','Uneven Texture','Reduce acne','Salicylic Acid, Azelaic Acid, Niacinamide','Heavy Oils, Lanolin'),
('Oily','Uneven Texture','Even skin tone','Retinol, Alpha Arbutin, Vitamin C','Fragrance, Harsh Acids'),
('Oily','Uneven Texture','Hydration','Panthenol, Glycerin, Aloe Vera','Alcohol, Sulfates'),

('Oily','Dullness','Glowing skin','Vitamin C, Glycolic Acid, Green Tea','Alcohol, Harsh Exfoliants'),
('Oily','Dullness','Reduce acne','Niacinamide, Salicylic Acid, Zinc PCA','Heavy Oils, Mineral Oil'),
('Oily','Dullness','Even skin tone','Alpha Arbutin, Retinol, Azelaic Acid','Fragrance, Harsh Acids'),
('Oily','Dullness','Hydration','Squalane, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

('Oily','Pigmentation','Glowing skin','Vitamin C, Niacinamide, Azelaic Acid','Fragrance, Strong Acids'),
('Oily','Pigmentation','Reduce acne','Azelaic Acid, Niacinamide, Retinol','Heavy Oils, Lanolin'),
('Oily','Pigmentation','Even skin tone','Alpha Arbutin, Licorice Root, Tranexamic Acid','Hydroquinone, Strong Peels'),
('Oily','Pigmentation','Hydration','Hyaluronic Acid, Panthenol, Aloe Vera','Alcohol, Sulfates'),

-- ================= DRY =================
('Dry','Dehydration','Glowing skin','Hyaluronic Acid, Niacinamide, Vitamin C','Alcohol, Sulfates'),
('Dry','Dehydration','Reduce acne','Azelaic Acid (gentle), Niacinamide','Benzoyl Peroxide, Strong Acids'),
('Dry','Dehydration','Even skin tone','Alpha Arbutin, Tranexamic Acid, Niacinamide','Harsh Acids, Alcohol'),
('Dry','Dehydration','Hydration','Hyaluronic Acid, Ceramides, Glycerin','Alcohol, Sulfates'),

('Dry','Sensitivity','Glowing skin','Niacinamide, Centella Asiatica, Panthenol','Fragrance, Essential Oils'),
('Dry','Sensitivity','Reduce acne','Azelaic Acid (low strength), Niacinamide','Salicylic Acid, Benzoyl Peroxide'),
('Dry','Sensitivity','Even skin tone','Licorice Root, Niacinamide, Centella Asiatica','Harsh Acids, Fragrance'),
('Dry','Sensitivity','Hydration','Ceramides, Shea Butter, Panthenol','Alcohol, Sulfates'),

('Dry','Aging','Glowing skin','Peptides, Vitamin C, Retinol (low strength)','Harsh Acids, Alcohol'),
('Dry','Aging','Reduce acne','Gentle Retinol, Niacinamide, Azelaic Acid','Benzoyl Peroxide, Harsh Acids'),
('Dry','Aging','Even skin tone','Retinol, Alpha Arbutin, Peptides','Fragrance, Harsh Acids'),
('Dry','Aging','Hydration','Ceramides, Hyaluronic Acid, Panthenol','Alcohol, Sulfates'),

('Dry','Dullness','Glowing skin','Vitamin C, Peptides, Squalane','Alcohol, Harsh Scrubs'),
('Dry','Dullness','Reduce acne','Niacinamide, Azelaic Acid, Gentle Retinol','Benzoyl Peroxide, Harsh Acids'),
('Dry','Dullness','Even skin tone','Alpha Arbutin, Licorice Root, Retinol','Fragrance, Harsh Acids'),
('Dry','Dullness','Hydration','Ceramides, Hyaluronic Acid, Panthenol','Alcohol, Sulfates'),

('Dry','Barrier Repair','Glowing skin','Ceramides, Niacinamide, Panthenol','Fragrance, Alcohol'),
('Dry','Barrier Repair','Reduce acne','Azelaic Acid (gentle), Niacinamide','Benzoyl Peroxide, Harsh Acids'),
('Dry','Barrier Repair','Even skin tone','Niacinamide, Licorice Root, Peptides','Harsh Acids, Fragrance'),
('Dry','Barrier Repair','Hydration','Ceramides, Shea Butter, Panthenol','Alcohol, Sulfates'),

-- ================= NORMAL =================
('Normal','Brightening','Glowing skin','Vitamin C, Niacinamide, Alpha Arbutin','Fragrance, Harsh Acids'),
('Normal','Brightening','Reduce acne','Niacinamide, Azelaic Acid','Harsh Benzoyl Peroxide, Alcohol'),
('Normal','Brightening','Even skin tone','Tranexamic Acid, Retinol, Niacinamide','Harsh Acids, Fragrance'),
('Normal','Brightening','Hydration','Hyaluronic Acid, Panthenol, Glycerin','Alcohol, Sulfates'),

('Normal','Pigmentation','Glowing skin','Vitamin C, Niacinamide, Retinol','Fragrance, Harsh Acids'),
('Normal','Pigmentation','Reduce acne','Azelaic Acid, Niacinamide, Retinol','Benzoyl Peroxide, Harsh Acids'),
('Normal','Pigmentation','Even skin tone','Tranexamic Acid, Alpha Arbutin, Azelaic Acid','Harsh Acids, Hydroquinone'),
('Normal','Pigmentation','Hydration','Hyaluronic Acid, Ceramides, Panthenol','Alcohol, Sulfates'),

('Normal','Dullness','Glowing skin','Vitamin C, Lactic Acid, Green Tea','Harsh Scrubs, Alcohol'),
('Normal','Dullness','Reduce acne','Niacinamide, Azelaic Acid, Retinol','Harsh Acids, Benzoyl Peroxide'),
('Normal','Dullness','Even skin tone','Alpha Arbutin, Licorice Root, Retinol','Harsh Acids, Fragrance'),
('Normal','Dullness','Hydration','Hyaluronic Acid, Panthenol, Squalane','Alcohol, Sulfates'),

('Normal','Dehydration','Glowing skin','Niacinamide, Vitamin C, Panthenol','Alcohol, Harsh Acids'),
('Normal','Dehydration','Reduce acne','Azelaic Acid, Niacinamide','Harsh Benzoyl Peroxide, Strong Acids'),
('Normal','Dehydration','Even skin tone','Alpha Arbutin, Tranexamic Acid, Niacinamide','Harsh Acids, Alcohol'),
('Normal','Dehydration','Hydration','Hyaluronic Acid, Glycerin, Ceramides','Alcohol, Sulfates'),

('Normal','Aging','Glowing skin','Vitamin C, Peptides, Retinol','Harsh Acids, Alcohol'),
('Normal','Aging','Reduce acne','Gentle Retinol, Azelaic Acid, Niacinamide','Benzoyl Peroxide, Harsh Acids'),
('Normal','Aging','Even skin tone','Retinol, Alpha Arbutin, Tranexamic Acid','Hydroquinone, Strong Peels'),
('Normal','Aging','Hydration','Ceramides, Hyaluronic Acid, Panthenol','Alcohol, Sulfates'),

-- ================= COMBINATION =================
('Combination','Acne','Glowing skin','Niacinamide, Green Tea, Zinc PCA','Heavy Oils, Lanolin'),
('Combination','Acne','Reduce acne','Salicylic Acid, Niacinamide, Clay','Coconut Oil, Mineral Oil'),
('Combination','Acne','Even skin tone','Azelaic Acid, Retinol, Alpha Arbutin','Fragrance, Harsh Acids'),
('Combination','Acne','Hydration','Aloe Vera, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

('Combination','Pigmentation','Glowing skin','Vitamin C, Niacinamide, Azelaic Acid','Fragrance, Strong Acids'),
('Combination','Pigmentation','Reduce acne','Azelaic Acid, Niacinamide, Retinol','Harsh Acids, Benzoyl Peroxide'),
('Combination','Pigmentation','Even skin tone','Alpha Arbutin, Tranexamic Acid, Retinol','Hydroquinone, Harsh Acids'),
('Combination','Pigmentation','Hydration','Hyaluronic Acid, Aloe Vera, Panthenol','Alcohol, Sulfates'),

('Combination','Dehydration','Glowing skin','Niacinamide, Vitamin C, Panthenol','Harsh Acids, Alcohol'),
('Combination','Dehydration','Reduce acne','Azelaic Acid, Niacinamide','Strong Acids, Benzoyl Peroxide'),
('Combination','Dehydration','Even skin tone','Alpha Arbutin, Retinol, Niacinamide','Harsh Acids, Fragrance'),
('Combination','Dehydration','Hydration','Hyaluronic Acid, Glycerin, Ceramides','Alcohol, Sulfates'),

('Combination','Large Pores','Glowing skin','Niacinamide, Retinol, Clay Mask','Heavy Oils, Petrolatum'),
('Combination','Large Pores','Reduce acne','Salicylic Acid, Clay, Zinc PCA','Coconut Oil, Lanolin'),
('Combination','Large Pores','Even skin tone','Retinol, Niacinamide, Lactic Acid','Harsh Scrubs, Fragrance'),
('Combination','Large Pores','Hydration','Green Tea, Aloe Vera, Panthenol','Alcohol, Sulfates'),

('Combination','Oil Control','Glowing skin','Niacinamide, Green Tea, Retinol','Heavy Oils, Mineral Oil'),
('Combination','Oil Control','Reduce acne','Zinc PCA, Salicylic Acid, Niacinamide','Coconut Oil, Lanolin'),
('Combination','Oil Control','Even skin tone','Azelaic Acid, Retinol, Niacinamide','Harsh Acids, Fragrance'),
('Combination','Oil Control','Hydration','Aloe Vera, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

('Combination','Uneven Texture','Glowing skin','Lactic Acid, Retinol, Niacinamide','Harsh Scrubs, Alcohol'),
('Combination','Uneven Texture','Reduce acne','Salicylic Acid, Azelaic Acid, Niacinamide','Harsh Acids, Benzoyl Peroxide'),
('Combination','Uneven Texture','Even skin tone','Retinol, Alpha Arbutin, Vitamin C','Fragrance, Harsh Acids'),
('Combination','Uneven Texture','Hydration','Panthenol, Glycerin, Aloe Vera','Alcohol, Sulfates'),

('Combination','Dullness','Glowing skin','Vitamin C, Green Tea, Peptides','Alcohol, Harsh Exfoliants'),
('Combination','Dullness','Reduce acne','Niacinamide, Salicylic Acid, Retinol','Benzoyl Peroxide, Harsh Acids'),
('Combination','Dullness','Even skin tone','Alpha Arbutin, Retinol, Azelaic Acid','Fragrance, Harsh Acids'),
('Combination','Dullness','Hydration','Squalane, Panthenol, Hyaluronic Acid','Alcohol, Sulfates'),

-- ================= SENSITIVE =================
('Sensitive','Redness','Glowing skin','Centella Asiatica, Niacinamide, Green Tea','Fragrance, Essential Oils'),
('Sensitive','Redness','Reduce acne','Azelaic Acid, Niacinamide','Benzoyl Peroxide, Strong Acids'),
('Sensitive','Redness','Even skin tone','Licorice Root, Niacinamide, Azelaic Acid','Harsh Acids, Fragrance'),
('Sensitive','Redness','Hydration','Oat Extract, Panthenol, Aloe Vera','Alcohol, Sulfates'),

('Sensitive','Sensitivity','Glowing skin','Niacinamide, Allantoin, Centella Asiatica','Fragrance, Strong Acids'),
('Sensitive','Sensitivity','Reduce acne','Azelaic Acid (gentle), Niacinamide','Benzoyl Peroxide, Harsh Acids'),
('Sensitive','Sensitivity','Even skin tone','Licorice Root, Niacinamide, Centella Asiatica','Fragrance, Harsh Acids'),
('Sensitive','Sensitivity','Hydration','Ceramides, Panthenol, Shea Butter','Alcohol, Sulfates'),

('Sensitive','Barrier Repair','Glowing skin','Ceramides, Niacinamide, Panthenol','Fragrance, Alcohol'),
('Sensitive','Barrier Repair','Reduce acne','Azelaic Acid (gentle), Niacinamide','Harsh Acids, Benzoyl Peroxide'),
('Sensitive','Barrier Repair','Even skin tone','Niacinamide, Licorice Root, Peptides','Harsh Acids, Fragrance'),
('Sensitive','Barrier Repair','Hydration','Ceramides, Panthenol, Shea Butter','Alcohol, Sulfates'),

('Sensitive','Dehydration','Glowing skin','Niacinamide, Vitamin C, Panthenol','Alcohol, Harsh Acids'),
('Sensitive','Dehydration','Reduce acne','Azelaic Acid, Niacinamide','Strong Acids, Benzoyl Peroxide'),
('Sensitive','Dehydration','Even skin tone','Alpha Arbutin, Retinol, Niacinamide','Fragrance, Harsh Acids'),
('Sensitive','Dehydration','Hydration','Hyaluronic Acid, Aloe Vera, Oat Extract','Alcohol, Sulfates'),

('Sensitive','Acne','Glowing skin','Niacinamide, Centella Asiatica, Zinc PCA','Heavy Oils, Lanolin'),
('Sensitive','Acne','Reduce acne','Azelaic Acid, Niacinamide, Centella Asiatica','Benzoyl Peroxide, Strong Acids'),
('Sensitive','Acne','Even skin tone','Retinol (low), Niacinamide, Azelaic Acid','Harsh Acids, Fragrance'),
('Sensitive','Acne','Hydration','Panthenol, Oat Extract, Aloe Vera','Alcohol, Sulfates')
""")



db.commit()

#this table is fixed and using faker will give inaccurate data so data is put manually

def table2():
	mycursor.execute("""CREATE TABLE User_Skin_Info (ID INT AUTO_INCREMENT PRIMARY KEY,User_id INT,Skin_type VARCHAR(100),Concern VARCHAR(100),Goal VARCHAR(100),Pregnant VARCHAR(100),Last_updated_at VARCHAR(50),Total_num_of_Quiz_taken INT,FOREIGN KEY (User_id) REFERENCES UserInfo(User_id))""")


def my_user_skin_info(n):
	#n=int(input("Enter no. of entries u want : "))
	data=[]
	User_ids = get_existing_ids('User_id','UserInfo')
	skin_ids = get_existing_ids('skin_id','SkinInfo')
	for _ in range(1,n+1):
		Last_updated_at=fake.date_time_this_year()
		User_id = random.choice(User_ids)  
		skin_id = random.choice(skin_ids) 
		Total_no_of_Quiz_taken=fake.random_int(min=0,max=8)
		#
		data.append((User_id,skin_id,Last_updated_at,Total_no_of_Quiz_taken))

	mycursor.execute("ALTER TABLE User_Skin_Info AUTO_INCREMENT=1")

	mycursor.executemany("INSERT INTO User_Skin_Info(User_id,skin_id,Last_updated_at,Total_num_of_Quiz_taken) VALUES (%s,%s,%s,%s) ",data)

	db.commit()

mycursor.execute("""CREATE TABLE Skin_Ingredient_Info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ingredient_name VARCHAR(255) NOT NULL,
    description TEXT,
    benefits TEXT,
    skin_type VARCHAR(50),
    avoid_for TEXT,
    notes TEXT
)""")

mycursor.execute("""INSERT INTO Skin_Ingredient_Info
(ingredient_name, description, benefits, skin_type, avoid_for, notes)
VALUES
('Hyaluronic Acid', 'Hydrates deeply by retaining moisture', 'Moisturizes, plumps skin', 'All', '', 'Safe for all skin types'),
('Niacinamide', 'Reduces redness, regulates oil, brightens skin tone', 'Controls oil, evens skin tone, reduces blemishes', 'Oily, Combination, Sensitive', '', 'Can be combined with most ingredients'),
('Salicylic Acid', 'Unclogs pores, exfoliates gently', 'Treats acne, exfoliates dead skin', 'Oily, Acne-prone', 'Dry, Sensitive', 'Use 2-3 times a week for sensitive skin'),
('Vitamin C', 'Brightens skin, reduces pigmentation, boosts collagen', 'Brightening, anti-aging, antioxidant', 'All', 'Sensitive', 'Use in morning with sunscreen'),
('Retinol', 'Improves cell turnover, reduces fine lines, clears acne', 'Anti-aging, acne treatment', 'All', 'Pregnant/Breastfeeding', 'Start with low concentration and gradually increase'),
('Ceramides', 'Strengthens skin barrier and locks in hydration', 'Moisturizes, protects skin barrier', 'Dry, Sensitive', '', 'Safe for daily use'),
('Aloe Vera', 'Soothes irritation and moisturizes', 'Calms redness, hydrates, anti-inflammatory', 'All', '', 'Can be used daily'),
('Shea Butter', 'Rich emollient for deep hydration', 'Moisturizes, nourishes dry skin', 'Dry', 'Oily, Acne-prone', 'Use in night creams or body creams'),
('Glycerin', 'Humectant that draws water into skin', 'Hydrates, softens skin', 'All', '', 'Safe for daily use'),
('Alpha Arbutin', 'Brightening ingredient that targets dark spots', 'Reduces hyperpigmentation, evens skin tone', 'All', '', 'Use with sunscreen in daytime'),
('Kojic Acid', 'Skin-brightening agent', 'Reduces pigmentation, brightens skin', 'All', 'Sensitive', 'Start with low concentration'),
('Panthenol', 'Pro-vitamin B5, moisturizes and heals', 'Hydrates, soothes, supports skin repair', 'All', '', 'Safe for daily use'),
('Lactic Acid', 'Gentle exfoliant (AHA)', 'Exfoliates, smooths texture, brightens', 'Dry, Combination', 'Sensitive', 'Use 1-2 times/week initially'),
('Glycolic Acid', 'Exfoliant (AHA) for brighter skin', 'Removes dead skin, improves texture', 'Oily, Combination', 'Sensitive', 'Use with sunscreen'),
('Zinc Oxide', 'Mineral sunscreen ingredient', 'Protects against UV, soothing', 'All', '', 'Safe for all skin types'),
('Titanium Dioxide', 'Mineral sunscreen ingredient', 'Protects against UV', 'All', '', 'Safe for daily use'),
('Peptides', 'Signal proteins to boost collagen', 'Reduces fine lines, firms skin', 'All', '', 'Use in serums or moisturizers'),
('Caffeine', 'Reduces puffiness and dark circles', 'De-puffs, brightens under-eye area', 'All', '', 'Apply in eye creams'),
('Green Tea Extract', 'Antioxidant, anti-inflammatory', 'Protects skin, reduces redness', 'All', '', 'Safe for daily use'),
('Chamomile Extract', 'Calming and soothing', 'Reduces irritation, anti-inflammatory', 'All', '', 'Gentle for sensitive skin'),
('Allantoin', 'Soothes and protects skin', 'Calms irritation, promotes healing', 'All', '', 'Safe for all skin types'),
('Sodium Hyaluronate', 'Smaller form of hyaluronic acid', 'Hydrates, penetrates deeper', 'All', '', 'Can layer with other serums'),
('L-Ascorbic Acid', 'Pure Vitamin C', 'Brightens, antioxidant, collagen booster', 'All', 'Sensitive', 'Use in morning with sunscreen'),
('Beta Glucan', 'Skin-soothing polysaccharide', 'Moisturizes, calms redness', 'All', '', 'Good for sensitive skin'),
('Ceramide NP', 'Specific ceramide for barrier repair', 'Restores barrier, locks moisture', 'Dry, Sensitive', '', 'Safe for daily use'),
('Squalane', 'Hydrating oil', 'Moisturizes, balances skin', 'All', '', 'Non-comedogenic, safe for acne-prone'),
('Azelaic Acid', 'Brightening and anti-acne', 'Reduces acne, pigmentation, redness', 'All', '', 'Use 1-2 times daily, morning/evening'),
('Cica (Centella Asiatica)', 'Soothes and heals skin', 'Reduces inflammation, repairs skin', 'All', '', 'Safe for sensitive skin'),
('Retinyl Palmitate', 'Gentler vitamin A derivative', 'Anti-aging, improves texture', 'All', 'Pregnant/Breastfeeding', 'Use at night'),
('Licorice Extract', 'Brightening and anti-inflammatory', 'Reduces pigmentation and redness', 'All', '', 'Safe for all skin types'),
('Panax Ginseng Extract', 'Antioxidant and revitalizing', 'Boosts circulation, brightens skin', 'All', '', 'Good for dull skin');
""")
db.commit()

def table3():
	mycursor.execute("CREATE TABLE Skin_Ingredient_Info (Ingredient_Id INT AUTO_INCREMENT PRIMARY KEY,Ingredient_name VARCHAR(100),Uses VARCHAR(200),avoid_in VARCHAR(200))")

def my_ingredient_info(n):
	#n=int(input("Enter no. of entries u want : "))
	ingredients = ["Salicylic Acid", "Niacinamide", "Vitamin C", "Retinol", "Hyaluronic Acid","Ceramides", "Zinc PCA", "Alpha Arbutin", "Lactic Acid", "Azelaic Acid","Peptides", "Glycolic Acid", "Centella Asiatica", "Green Tea", "Panthenol","Allantoin", "Licorice Root", "Squalane", "Ferulic Acid", "Clay"]

	uses_options = ["Treats acne", "Brightens skin", "Evens skin tone", "Hydrates deeply", "Reduces fine lines", "Soothes inflammation", "Minimizes pores", "Strengthens skin barrier", "Reduces pigmentation", "Controls oil"]

	avoid_in_options = ["Sensitive skin", "Pregnancy", "Sun exposure", "Dry skin", "Rosacea", "Broken skin", "Eczema", "Allergy-prone skin", "Over-exfoliated skin", "Retinol routine"]
	#some inputs are fixed and can't be generated from faker 
	data = []
	for _ in range(1,n+1):
		Ingredient_name = random.choice(ingredients)
		Uses = random.choice(uses_options)
		avoid_in = random.choice(avoid_in_options)
		data.append((Ingredient_name, Uses, avoid_in))

	mycursor.execute("ALTER TABLE Skin_Ingredient_Info AUTO_INCREMENT=1")
	mycursor.executemany("INSERT INTO Skin_Ingredient_Info(Ingredient_name,Uses,avoid_in) VALUES(%s,%s,%s) ",data)

	db.commit()


def table4():
mycursor.execute("CREATE TABLE Feedback_Info(Feedback_Id INT AUTO_INCREMENT PRIMARY KEY,User_id INT,Skin_Id INT,Feedback VARCHAR(200),FOREIGN KEY (User_Id) REFERENCES UserInfo (User_id),FOREIGN KEY (Skin_Id) REFERENCES SkinInfo(Skin_Id))")

def get_random_feedback(max_chars=100):
    return fake.text(max_nb_chars=max_chars).strip()


def my_feedback_table(n):
	#n=int(input("Enter no. of entries u want : "))
	data=[]
	user_ids = get_existing_ids('User_id','UserInfo') 
	skin_ids = get_existing_ids('skin_id','SkinInfo') #here random user and skin ids are used to get general layout of expected table
	for _ in range(1,n+1):
		User_id = random.choice(user_ids)
		Skin_Id = random.choice(skin_ids)
		Feedback = get_random_feedback() 		#feedback is user generated so faker is used for it  
		data.append((User_id, Skin_Id, Feedback))

	mycursor.execute("ALTER TABLE Feedback_Info AUTO_INCREMENT=1")
	insert_data = "INSERT INTO Feedback_Info(User_Id,Skin_Id,Feedback) VALUES(%s,%s,%s)"
	mycursor.executemany(insert_data,data)
	db.commit()

mycursor.execute("CREATE TABLE product_info(product_id INT AUTO_INCREMENT PRIMARY KEY,Brand_name VARCHAR(100),Product_name VARCHAR(200),gender VARCHAR(100),Discount VARCHAR(200),Price INT,skin_type VARCHAR(500),ingredients VARCHAR(500),benefits VARCHAR(500),concern VARCHAR(200))")




sql = """
INSERT INTO product_info 
(Brand_name, Product_name, gender, Discount, Price, skin_type, ingredients, benefits, concern) 
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# 3. Your raw data (CSV style, you can load from file too)
data = """Caudalie,Caudalie Vinoperfect Brightening Dark Spot Serum (30 ml),Unisex,,6250,All Skin Types,['Olive-Oil'],['Skin-Plumping'],['Pigmentation']
WishCare,WishCare Niacinamide Oil Balance Sunscreen SPF 50 PA++++ (50 g),Unisex,20% OFF,399,All Skin Types,"['Ceramides', 'Zinc-Oxide', 'Niacinamide']","['Sun-Protection', 'Non-Sticky', 'Brightening']","['Sun-Damage', 'Oil-Control', 'Blemishes']"
Insight Cosmetics,Insight Cosmetics Pro Concealer Palette - Corrector (15g),nil,10% OFF,216,All Skin Types,[],[],[]
The Face Shop,The Face Shop Brightening Combo for Dry Skin,Women,10% OFF,2307,All Skin Types,"['Ceramides', 'Glycerin']","['Hydrating', 'Moisturising', 'Smoothening']",['Pores']
Minimalist,"Minimalist 10% Vitamin B5 Face Moisturizer For Oily acne prone Skin Cream With Zn, Cu, Mg & Ha (50g)",Unisex,5% OFF,331,Oily,['Vitamin B5'],['Hydrating'],['Blemishes']
"""

# 4. Read it like CSV
reader = csv.reader(data.splitlines())

for row in reader:
    # row is a list like [Brand_name, Product_name, gender, Discount, Price, skin_type, ingredients, benefits, concern]

    # Handle empty values -> None
    row = [None if field == '' else field for field in row]

    # Convert list-looking strings into clean text
    for i in range(6, 9):  # ingredients, benefits, concern are columns 6,7,8
        if row[i]:
            try:
                # Convert string "['a','b']" into actual Python list, then join
                parsed = ast.literal_eval(row[i])
                if isinstance(parsed, list):
                    row[i] = ", ".join(parsed)
            except Exception:
                # If it fails, keep as is
                pass

    # Execute insert
    mycursor.execute(sql, tuple(row))

# 5. Commit changes
db.commit()
print("Data inserted successfully!")

mycursor.close()
db.close()

mycursor.execute("CREATE TABLE diet_info(diet_id INT AUTO_INCREMENT PRIMARY KEY,skin_type VARCHAR(200), concern VARCHAR(200),skin_goal VARCHAR(100),recommendations VARCHAR(500), to_avoid VARCHAR(500))")

mycursor.execute("""
INSERT INTO diet_info (skin_type, concern, skin_goal, recommendations, to_avoid) VALUES
-- ================= OILY =================
('Oily','Acne','Glowing skin','Leafy greens, cucumber, tomatoes, green tea, flax seeds, yogurt','Fried foods, excess dairy, processed sugar, soda'),
('Oily','Acne','Reduce acne','Lentils, sprouts, bitter gourd, turmeric, green tea','Fried snacks, cheese, ice cream, refined sugar'),
('Oily','Acne','Even skin tone','Citrus fruits, papaya, carrots, turmeric, berries','Packaged foods, fried items, excess sweets'),
('Oily','Acne','Hydration','Watermelon, cucumber, coconut water, oranges, spinach','Alcohol, salty packaged foods'),

('Oily','Large Pores','Glowing skin','Tomatoes, carrots, citrus fruits, green tea, walnuts','Junk food, sugary drinks'),
('Oily','Large Pores','Reduce acne','Cucumber, bitter gourd, leafy greens, probiotic yogurt','Fried food, heavy dairy'),
('Oily','Large Pores','Even skin tone','Papaya, citrus fruits, turmeric, beetroot, berries','Processed sugar, refined carbs'),
('Oily','Large Pores','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, packaged chips'),

('Oily','Oil Control','Glowing skin','Green tea, cucumber, tomatoes, flax seeds, sprouts','Heavy fried snacks, oily gravies'),
('Oily','Oil Control','Reduce acne','Leafy greens, bitter gourd, turmeric, cucumbers','Pizza, cheese, processed sugar'),
('Oily','Oil Control','Even skin tone','Citrus fruits, papaya, berries, turmeric milk','Deep fried snacks, refined sugar'),
('Oily','Oil Control','Hydration','Watermelon, coconut water, cucumbers, spinach','Alcohol, excess coffee'),

('Oily','Uneven Texture','Glowing skin','Carrots, tomatoes, citrus fruits, almonds, green tea','Fried foods, sodas'),
('Oily','Uneven Texture','Reduce acne','Sprouts, cucumbers, bitter gourd, turmeric','Processed dairy, fried food'),
('Oily','Uneven Texture','Even skin tone','Papaya, oranges, turmeric milk, beetroot','Packaged sugar, junk food'),
('Oily','Uneven Texture','Hydration','Coconut water, cucumber, spinach, watermelon','Alcohol, too much coffee'),

('Oily','Dullness','Glowing skin','Citrus fruits, papaya, green tea, beetroot juice','Fried foods, processed snacks'),
('Oily','Dullness','Reduce acne','Leafy greens, turmeric, cucumbers, lentils','Excess dairy, refined sugar'),
('Oily','Dullness','Even skin tone','Carrots, berries, tomatoes, citrus fruits','Fried junk, too much caffeine'),
('Oily','Dullness','Hydration','Watermelon, cucumber, coconut water, spinach','Alcohol, salty chips'),

('Oily','Pigmentation','Glowing skin','Papaya, citrus fruits, berries, turmeric milk','Fried snacks, refined carbs'),
('Oily','Pigmentation','Reduce acne','Leafy greens, turmeric, cucumbers, flax seeds','Excess sugar, deep fried items'),
('Oily','Pigmentation','Even skin tone','Berries, citrus fruits, beetroot, tomatoes','Packaged sweets, sodas'),
('Oily','Pigmentation','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, processed snacks'),

-- ================= DRY =================
('Dry','Dehydration','Glowing skin','Avocado, nuts, seeds, olive oil, coconut water','Fried foods, processed snacks, excess sugar'),
('Dry','Dehydration','Reduce acne','Oats, spinach, pumpkin seeds, chia seeds','Cheese, fried items, sugary drinks'),
('Dry','Dehydration','Even skin tone','Papaya, berries, kiwi, walnuts','Packaged sugar, fried foods'),
('Dry','Dehydration','Hydration','Cucumber, coconut water, watermelon, oranges','Alcohol, excess caffeine'),

('Dry','Sensitivity','Glowing skin','Oatmeal, aloe vera, bananas, green tea','Spicy foods, fried items, alcohol'),
('Dry','Sensitivity','Reduce acne','Cucumber, turmeric, leafy greens, probiotic yogurt','Hot spices, processed food, cheese'),
('Dry','Sensitivity','Even skin tone','Papaya, carrots, blueberries, almonds','Fried food, refined sugar'),
('Dry','Sensitivity','Hydration','Watermelon, cucumber, coconut water, spinach','Alcohol, packaged snacks'),

('Dry','Aging','Glowing skin','Berries, nuts, seeds, green tea, avocado','Excess sugar, fried foods, alcohol'),
('Dry','Aging','Reduce acne','Spinach, turmeric, oats, chia seeds','Fried snacks, refined carbs'),
('Dry','Aging','Even skin tone','Papaya, citrus fruits, walnuts, flax seeds','Processed sugar, deep fried items'),
('Dry','Aging','Hydration','Cucumber, coconut water, oranges, watermelon','Alcohol, salty snacks'),

('Dry','Dullness','Glowing skin','Carrots, papaya, berries, almonds, green tea','Fried foods, soda, processed snacks'),
('Dry','Dullness','Reduce acne','Spinach, cucumber, lentils, turmeric','Excess cheese, fried items'),
('Dry','Dullness','Even skin tone','Citrus fruits, beetroot, papaya, flax seeds','Packaged sugar, junk food'),
('Dry','Dullness','Hydration','Coconut water, watermelon, cucumber, kiwi','Alcohol, packaged snacks'),

('Dry','Barrier Repair','Glowing skin','Avocado, nuts, seeds, olive oil, green tea','Fried foods, processed snacks'),
('Dry','Barrier Repair','Reduce acne','Spinach, lentils, turmeric, cucumber','Excess dairy, deep fried foods'),
('Dry','Barrier Repair','Even skin tone','Papaya, berries, carrots, walnuts','Packaged sugar, fried items'),
('Dry','Barrier Repair','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, processed foods'),

-- ================= NORMAL =================
('Normal','Brightening','Glowing skin','Berries, citrus fruits, papaya, green tea, carrots','Fried foods, soda, processed snacks'),
('Normal','Brightening','Reduce acne','Spinach, cucumber, turmeric, lentils','Excess dairy, fried items'),
('Normal','Brightening','Even skin tone','Papaya, oranges, beetroot, flax seeds','Packaged sugar, junk food'),
('Normal','Brightening','Hydration','Coconut water, watermelon, cucumber, kiwi','Alcohol, processed snacks'),

('Normal','Pigmentation','Glowing skin','Berries, citrus fruits, tomatoes, walnuts','Fried foods, sugar, processed snacks'),
('Normal','Pigmentation','Reduce acne','Spinach, turmeric, cucumber, lentils','Cheese, fried foods, sugary drinks'),
('Normal','Pigmentation','Even skin tone','Papaya, beetroot, citrus fruits, flax seeds','Packaged sweets, deep fried snacks'),
('Normal','Pigmentation','Hydration','Coconut water, watermelon, cucumber, oranges','Alcohol, packaged snacks'),

('Normal','Dullness','Glowing skin','Carrots, berries, papaya, green tea, almonds','Fried foods, soda, processed items'),
('Normal','Dullness','Reduce acne','Spinach, cucumber, lentils, turmeric','Excess cheese, fried items'),
('Normal','Dullness','Even skin tone','Papaya, citrus fruits, beetroot, flax seeds','Packaged sugar, junk food'),
('Normal','Dullness','Hydration','Coconut water, watermelon, cucumber, kiwi','Alcohol, processed snacks'),

('Normal','Dehydration','Glowing skin','Avocado, nuts, seeds, olive oil, green tea','Fried foods, sugar, processed snacks'),
('Normal','Dehydration','Reduce acne','Oats, spinach, pumpkin seeds, chia seeds','Fried foods, cheese, sugary drinks'),
('Normal','Dehydration','Even skin tone','Papaya, berries, kiwi, walnuts','Packaged sugar, fried foods'),
('Normal','Dehydration','Hydration','Cucumber, coconut water, watermelon, oranges','Alcohol, excess caffeine'),

('Normal','Aging','Glowing skin','Berries, nuts, seeds, avocado, green tea','Excess sugar, fried items, alcohol'),
('Normal','Aging','Reduce acne','Spinach, turmeric, oats, chia seeds','Fried snacks, refined carbs'),
('Normal','Aging','Even skin tone','Papaya, citrus fruits, walnuts, flax seeds','Processed sugar, deep fried items'),

-- ================= COMBINATION =================
('Combination','Acne','Glowing skin','Leafy greens, cucumber, tomatoes, green tea, flax seeds','Fried foods, excess dairy, processed sugar'),
('Combination','Acne','Reduce acne','Lentils, sprouts, bitter gourd, turmeric, green tea','Fried snacks, cheese, ice cream, refined sugar'),
('Combination','Acne','Even skin tone','Citrus fruits, papaya, carrots, turmeric, berries','Packaged foods, fried items, excess sweets'),
('Combination','Acne','Hydration','Watermelon, cucumber, coconut water, oranges, spinach','Alcohol, salty packaged foods'),

('Combination','Pigmentation','Glowing skin','Papaya, citrus fruits, berries, turmeric milk','Fried snacks, refined carbs'),
('Combination','Pigmentation','Reduce acne','Leafy greens, turmeric, cucumbers, flax seeds','Excess sugar, deep fried items'),
('Combination','Pigmentation','Even skin tone','Berries, citrus fruits, beetroot, tomatoes','Packaged sweets, sodas'),
('Combination','Pigmentation','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, processed snacks'),

('Combination','Dehydration','Glowing skin','Avocado, nuts, seeds, olive oil, coconut water','Fried foods, processed snacks, excess sugar'),
('Combination','Dehydration','Reduce acne','Oats, spinach, pumpkin seeds, chia seeds','Cheese, fried items, sugary drinks'),
('Combination','Dehydration','Even skin tone','Papaya, berries, kiwi, walnuts','Packaged sugar, fried foods'),
('Combination','Dehydration','Hydration','Cucumber, coconut water, watermelon, oranges','Alcohol, excess caffeine'),

-- ================= COMBINATION =================
('Combination','Large Pores','Glowing skin','Tomatoes, carrots, citrus fruits, green tea, walnuts','Junk food, sugary drinks'),
('Combination','Large Pores','Reduce acne','Cucumber, bitter gourd, leafy greens, probiotic yogurt','Fried food, heavy dairy'),
('Combination','Large Pores','Even skin tone','Papaya, citrus fruits, turmeric, beetroot, berries','Processed sugar, refined carbs'),
('Combination','Large Pores','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, packaged chips'),

('Combination','Oil Control','Glowing skin','Green tea, cucumber, tomatoes, flax seeds, sprouts','Heavy fried snacks, oily gravies'),
('Combination','Oil Control','Reduce acne','Leafy greens, bitter gourd, turmeric, cucumbers','Pizza, cheese, processed sugar'),
('Combination','Oil Control','Even skin tone','Citrus fruits, papaya, berries, turmeric milk','Deep fried snacks, refined sugar'),
('Combination','Oil Control','Hydration','Watermelon, coconut water, cucumbers, spinach','Alcohol, excess coffee'),

('Combination','Uneven Texture','Glowing skin','Carrots, tomatoes, citrus fruits, almonds, green tea','Fried foods, sodas'),
('Combination','Uneven Texture','Reduce acne','Sprouts, cucumbers, bitter gourd, turmeric','Processed dairy, fried food'),
('Combination','Uneven Texture','Even skin tone','Papaya, oranges, turmeric milk, beetroot','Packaged sugar, junk food'),
('Combination','Uneven Texture','Hydration','Coconut water, cucumber, spinach, watermelon','Alcohol, too much coffee'),

('Combination','Dullness','Glowing skin','Citrus fruits, papaya, green tea, beetroot juice','Fried foods, processed snacks'),
('Combination','Dullness','Reduce acne','Leafy greens, turmeric, cucumbers, lentils','Excess dairy, refined sugar'),
('Combination','Dullness','Even skin tone','Carrots, berries, tomatoes, citrus fruits','Fried junk, too much caffeine'),
('Combination','Dullness','Hydration','Watermelon, cucumber, coconut water, spinach','Alcohol, salty chips'),

-- ================= SENSITIVE =================
('Sensitive','Redness','Glowing skin','Oatmeal, aloe vera, bananas, green tea','Spicy foods, fried items, alcohol'),
('Sensitive','Redness','Reduce acne','Cucumber, turmeric, leafy greens, probiotic yogurt','Hot spices, processed food, cheese'),
('Sensitive','Redness','Even skin tone','Papaya, carrots, blueberries, almonds','Fried food, refined sugar'),
('Sensitive','Redness','Hydration','Watermelon, cucumber, coconut water, spinach','Alcohol, packaged snacks'),

('Sensitive','Sensitivity','Glowing skin','Oatmeal, aloe vera, bananas, green tea','Spicy foods, fried items, alcohol'),
('Sensitive','Sensitivity','Reduce acne','Cucumber, turmeric, leafy greens, probiotic yogurt','Hot spices, processed food, cheese'),
('Sensitive','Sensitivity','Even skin tone','Papaya, carrots, blueberries, almonds','Fried food, refined sugar'),
('Sensitive','Sensitivity','Hydration','Watermelon, cucumber, coconut water, spinach','Alcohol, packaged snacks'),

('Sensitive','Barrier Repair','Glowing skin','Avocado, nuts, seeds, olive oil, green tea','Fried foods, processed snacks'),
('Sensitive','Barrier Repair','Reduce acne','Spinach, lentils, turmeric, cucumber','Excess dairy, deep fried foods'),
('Sensitive','Barrier Repair','Even skin tone','Papaya, berries, carrots, walnuts','Packaged sugar, fried items'),
('Sensitive','Barrier Repair','Hydration','Coconut water, watermelon, cucumber, spinach','Alcohol, processed foods'),

('Sensitive','Dehydration','Glowing skin','Avocado, nuts, seeds, olive oil, coconut water','Fried foods, processed snacks, excess sugar'),
('Sensitive','Dehydration','Reduce acne','Oats, spinach, pumpkin seeds, chia seeds','Cheese, fried items, sugary drinks'),
('Sensitive','Dehydration','Even skin tone','Papaya, berries, kiwi, walnuts','Packaged sugar, fried foods'),
('Sensitive','Dehydration','Hydration','Cucumber, coconut water, watermelon, oranges','Alcohol, excess caffeine'),

('Sensitive','Acne','Glowing skin','Leafy greens, cucumber, tomatoes, green tea, flax seeds','Fried foods, excess dairy, processed sugar'),
('Sensitive','Acne','Reduce acne','Lentils, sprouts, bitter gourd, turmeric, green tea','Fried snacks, cheese, ice cream, refined sugar'),
('Sensitive','Acne','Even skin tone','Citrus fruits, papaya, carrots, turmeric, berries','Packaged foods, fried items, excess sweets'),
('Sensitive','Acne','Hydration','Watermelon, cucumber, coconut water, oranges, spinach','Alcohol, salty packaged foods');
""")



db.commit()


mycursor.execute("""
CREATE TABLE IF NOT EXISTS SkinInfo (
    skin_id INT AUTO_INCREMENT PRIMARY KEY,
    skin_type VARCHAR(50),
    concern VARCHAR(100),
    description TEXT,
    am_routine TEXT,
    pm_routine TEXT
)
""")



mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Oily + Acne
('Oily', 'Acne',
 'Oily skin produces excess sebum, making it prone to breakouts and clogged pores. A targeted routine controls oil and reduces acne.',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser — Removes excess oil and impurities",
   "Treatment": "The Ordinary Salicylic Acid 2% — Clears acne and unclogs pores",
   "Moisturizer": "Neutrogena Hydro Boost Water Gel — Lightweight hydration",
   "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Broad-spectrum oil-free protection"}',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser — Deep cleanses without over-drying",
   "Treatment": "Paula’s Choice 2% BHA Liquid Exfoliant — Prevents clogged pores",
   "Moisturizer": "Neutrogena Hydro Boost Water Gel — Hydrates overnight"}'),

-- Oily + Large Pores
('Oily', 'Large Pores',
 'Oily skin often develops enlarged pores due to excess sebum and buildup. Niacinamide helps refine pores and balance skin.',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser — Controls excess oil",
   "Treatment": "The Ordinary Niacinamide 10% + Zinc 1% — Minimizes pores",
   "Moisturizer": "Plum Green Tea Oil-Free Moisturizer — Lightweight hydration",
   "Sunscreen": "Minimalist Sunscreen SPF 50 — Oil-control formula"}',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser — Maintains balance",
   "Treatment": "Retinol Serum (0.2–0.5%) — Smooths skin & reduces pore appearance",
   "Moisturizer": "Plum Green Tea Oil-Free Moisturizer — Non-comedogenic hydration"}'),

-- Oily + Oil Control
('Oily', 'Oil Control',
 'Excess sebum makes oily skin shiny and prone to acne. A routine focusing on oil regulation, hydration, and gentle exfoliation keeps skin balanced.',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator — Removes excess oil",
   "Treatment": "Niacinamide 10% Serum — Regulates sebum production",
   "Moisturizer": "Clinique Dramatically Different Oil-Free Gel — Lightweight hydration",
   "Sunscreen": "Neutrogena Clear Face SPF 50 — Matte finish"}',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator — Keeps skin fresh",
   "Treatment": "The Ordinary Salicylic Acid 2% — Prevents breakouts",
   "Moisturizer": "Clinique Dramatically Different Oil-Free Gel — Non-greasy hydration"}'),

-- Oily + Uneven Texture
('Oily', 'Uneven Texture',
 'Oily skin can develop rough texture due to excess oil and dead skin buildup. Exfoliation and lightweight hydration help smooth the skin.',
 '{"Cleanser": "Cetaphil Oily Skin Cleanser — Gentle daily foaming wash",
   "Treatment": "The Ordinary Glycolic Acid 7% Toning Solution — Exfoliates dead skin",
   "Moisturizer": "Belif Aqua Bomb — Lightweight gel hydration",
   "Sunscreen": "Biore UV Aqua Rich SPF 50 — Weightless UV protection"}',
 '{"Cleanser": "Cetaphil Oily Skin Cleanser — Balances sebum",
   "Treatment": "The Ordinary Retinol 0.2–0.5% — Refines uneven skin",
   "Moisturizer": "Belif Aqua Bomb — Locks hydration overnight"}'),

-- Oily + Dullness
('Oily', 'Dullness',
 'Oily skin may appear lackluster despite shine, due to clogged pores and dead skin buildup. Brightening routines improve radiance.',
 '{"Cleanser": "CeraVe Foaming Cleanser — Clears impurities",
   "Treatment": "La Roche-Posay Pure Vitamin C10 Serum — Brightens dull skin",
   "Moisturizer": "Olay Luminous Whip Moisturizer — Lightweight brightening hydration",
   "Sunscreen": "Eucerin Sun Fluid SPF 50 — Prevents pigmentation"}',
 '{"Cleanser": "CeraVe Foaming Cleanser — Preps skin for actives",
   "Treatment": "The Ordinary AHA 7% Toning Solution — Gentle exfoliation & glow",
   "Moisturizer": "Olay Luminous Whip Moisturizer — Improves radiance overnight"}'),

-- Oily + Pigmentation
('Oily', 'Pigmentation',
 'Oily skin with pigmentation needs targeted brightening and exfoliation while controlling excess oil.',
 '{"Cleanser": "Simple Refreshing Facial Wash — Gentle oil-free cleanser",
   "Treatment": "The Ordinary Alpha Arbutin 2% + HA — Reduces pigmentation",
   "Moisturizer": "Neutrogena Hydro Boost Water Gel — Lightweight hydration",
   "Sunscreen": "La Roche-Posay Anthelios UVMune 400 SPF 50+ — Prevents pigmentation"}',
 '{"Cleanser": "Simple Refreshing Facial Wash — Maintains balance",
   "Treatment": "The Ordinary Azelaic Acid 10% — Evens skin tone",
   "Moisturizer": "Neutrogena Hydro Boost Water Gel — Hydration & repair"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Dry + Dehydration
('Dry', 'Dehydration',
 'Dry skin lacks water content, making it prone to tightness and flakiness. Hydrating routines restore moisture and maintain skin barrier.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle, non-stripping",
   "Treatment": "The Ordinary Hyaluronic Acid 2% + B5 — Deep hydration",
   "Moisturizer": "Neutrogena Hydro Boost Cream — Locks in moisture",
   "Sunscreen": "La Roche-Posay Anthelios Melt-in SPF 50 — Non-drying"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Maintains moisture",
   "Treatment": "The Inkey List Hyaluronic Acid Serum — Overnight hydration",
   "Moisturizer": "CeraVe Moisturizing Cream — Nourishes and repairs"}'),

-- Dry + Sensitivity
('Dry', 'Sensitivity',
 'Sensitive dry skin can react easily to products. Gentle and soothing routines reduce irritation and calm the skin.',
 '{"Cleanser": "La Roche-Posay Toleriane Hydrating Gentle Cleanser — Minimal irritation",
   "Treatment": "Avene Cicalfate Restorative Cream — Calms redness and inflammation",
   "Moisturizer": "Belif Moisturizing Bomb — Soothes and hydrates",
   "Sunscreen": "EltaMD UV Physical SPF 41 — Gentle mineral sunscreen"}',
 '{"Cleanser": "La Roche-Posay Toleriane Cleanser — Keeps barrier intact",
   "Treatment": "Dr. Jart Cicapair Tiger Grass Serum — Reduces sensitivity",
   "Moisturizer": "Belif Moisturizing Bomb — Locks hydration overnight"}'),

-- Dry + Aging
('Dry', 'Aging',
 'Dry skin loses elasticity and may show fine lines. Anti-aging routines with hydration and antioxidants help maintain youthful skin.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle and nourishing",
   "Treatment": "The Ordinary Buffet + Copper Peptides — Targets fine lines",
   "Moisturizer": "Olay Regenerist Micro-Sculpting Cream — Anti-aging hydration",
   "Sunscreen": "Neutrogena Hydro Boost SPF 50 — Protects from UV aging"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Prepares skin for night actives",
   "Treatment": "Retinol 0.2–0.5% Serum — Reduces fine lines",
   "Moisturizer": "Olay Regenerist Night Cream — Overnight repair"}'),

-- Dry + Dullness
('Dry', 'Dullness',
 'Dry skin can appear lifeless due to lack of moisture and dead cell buildup. Brightening and hydration restore radiance.',
 '{"Cleanser": "Aveeno Positively Radiant Gentle Cleanser — Hydrating",
   "Treatment": "Vitamin C Serum (La Roche-Posay Pure Vitamin C10) — Brightens skin",
   "Moisturizer": "Clinique Moisture Surge — Lightweight hydration",
   "Sunscreen": "Eucerin Sun Fluid SPF 50 — Protects and prevents dullness"}',
 '{"Cleanser": "Aveeno Positively Radiant Cleanser — Removes impurities",
   "Treatment": "The Ordinary AHA 7% Toning Solution — Gentle exfoliation for glow",
   "Moisturizer": "Clinique Moisture Surge — Overnight radiance"}'),

-- Dry + Barrier Repair
('Dry', 'Barrier Repair',
 'Dry skin with a compromised barrier is prone to sensitivity, redness, and moisture loss. Routine strengthens and restores the barrier.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Maintains natural lipids",
   "Treatment": "La Roche-Posay Cicaplast Baume B5 — Repairs barrier",
   "Moisturizer": "Vanicream Moisturizing Cream — Rich hydration",
   "Sunscreen": "EltaMD UV Physical SPF 41 — Gentle protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle evening wash",
   "Treatment": "Avene Cicalfate Repair Cream — Supports skin recovery",
   "Moisturizer": "Vanicream Moisturizing Cream — Nourishing overnight"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Normal + Brightening
('Normal', 'Brightening',
 'Normal skin looks healthy but can lose radiance over time. Brightening routines maintain glow and prevent dullness.',
 '{"Cleanser": "Fresh Soy Face Cleanser — Gentle and brightening",
   "Treatment": "Vitamin C Serum (SkinCeuticals C E Ferulic) — Boosts radiance",
   "Moisturizer": "Clinique Moisture Surge — Lightweight hydration",
   "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Broad-spectrum"}',
 '{"Cleanser": "Fresh Soy Face Cleanser — Cleanses without stripping",
   "Treatment": "The Ordinary AHA 7% Toning Solution — Gentle exfoliation",
   "Moisturizer": "Clinique Moisture Surge — Locks in moisture"}'),

-- Normal + Pigmentation
('Normal', 'Pigmentation',
 'Normal skin can develop dark spots due to sun or hormonal changes. Targeted routines reduce pigment formation.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Maintains skin balance",
   "Treatment": "Kiehl’s Clearly Corrective Dark Spot Solution — Reduces pigmentation",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Protects against dark spots"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Preps skin for night treatments",
   "Treatment": "The Ordinary Alpha Arbutin 2% + HA — Targets spots",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Hydrates overnight"}'),

-- Normal + Dullness
('Normal', 'Dullness',
 'Normal skin may appear lackluster due to pollution, fatigue, or buildup. Brightening and hydration restore glow.',
 '{"Cleanser": "Aveeno Positively Radiant Cleanser — Gentle cleansing",
   "Treatment": "Vitamin C Serum (La Roche-Posay Pure Vitamin C10) — Revives radiance",
   "Moisturizer": "Belif Moisturizing Bomb — Refreshing hydration",
   "Sunscreen": "Neutrogena Ultra Sheer SPF 50 — Protects skin glow"}',
 '{"Cleanser": "Aveeno Positively Radiant Cleanser — Cleanses impurities",
   "Treatment": "The Ordinary Lactic Acid 5% — Light exfoliation for glow",
   "Moisturizer": "Belif Moisturizing Bomb — Locks hydration"}'),

-- Normal + Dehydration
('Normal', 'Dehydration',
 'Even normal skin can become dehydrated due to environment or habits. Hydrating routines restore water balance.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Maintains moisture",
   "Treatment": "Hyaluronic Acid Serum (The Ordinary) — Deep hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Locks in water",
   "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Broad protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle cleansing",
   "Treatment": "Hyaluronic Acid Serum — Overnight hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Keeps skin supple"}'),

-- Normal + Aging
('Normal', 'Aging',
 'Normal skin over time shows early signs of aging. Anti-aging routines maintain elasticity and prevent fine lines.',
 '{"Cleanser": "Fresh Soy Face Cleanser — Gentle and nourishing",
   "Treatment": "The Ordinary Buffet + Copper Peptides — Prevents early aging",
   "Moisturizer": "Olay Regenerist Micro-Sculpting Cream — Hydrates and firms",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Protects against premature aging"}',
 '{"Cleanser": "Fresh Soy Face Cleanser — Prepares skin for night actives",
   "Treatment": "Retinol 0.2–0.5% Serum — Smooths fine lines",
   "Moisturizer": "Olay Regenerist Night Cream — Overnight repair"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Combination + Acne
('Combination', 'Acne',
 'Combination skin can break out due to oilier zones (T-zone). Targeted routines balance oil and prevent acne.',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Controls oil without drying",
   "Treatment": "The Ordinary Niacinamide 10% + Zinc 1% — Reduces breakouts",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Non-greasy protection"}',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Removes impurities",
   "Treatment": "Paula’s Choice 2% BHA Liquid Exfoliant — Prevents clogged pores",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Hydrates dry areas"}'),

-- Combination + Pigmentation
('Combination', 'Pigmentation',
 'Combination skin may develop uneven skin tone due to sun and hormonal factors. Brightening routines restore clarity.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle cleansing",
   "Treatment": "Kiehl’s Clearly Corrective Dark Spot Solution — Reduces pigmentation",
   "Moisturizer": "Belif Moisturizing Bomb — Maintains hydration",
   "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Broad-spectrum protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "The Ordinary Alpha Arbutin 2% + HA — Target dark spots",
   "Moisturizer": "Belif Moisturizing Bomb — Locks moisture"}'),

-- Combination + Dehydration
('Combination', 'Dehydration',
 'Even combination skin can get dehydrated in drier zones. Hydrating routines restore balance.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Non-stripping",
   "Treatment": "Hyaluronic Acid Serum (The Ordinary) — Boosts hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Hydration and protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "Hyaluronic Acid Serum — Night hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream"}'),

-- Combination + Large Pores
('Combination', 'Large Pores',
 'Excess sebum and dead skin cause enlarged pores in combination skin. Pore-minimizing routines help refine skin texture.',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator — Controls oil",
   "Treatment": "The Ordinary Niacinamide 10% + Zinc 1% — Minimizes pores",
   "Moisturizer": "Oil-free gel moisturizer",
   "Sunscreen": "SPF 50 broad-spectrum"}',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator",
   "Treatment": "Retinol 0.2–0.5% serum — Reduces pore appearance",
   "Moisturizer": "Lightweight gel moisturizer"}'),

-- Combination + Oil Control
('Combination', 'Oil Control',
 'Combination skin requires balancing oily and dry zones. Focus on gentle oil control and hydration.',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Controls oil",
   "Treatment": "Niacinamide Serum — Reduces excess sebum",
   "Moisturizer": "Lightweight gel moisturizer",
   "Sunscreen": "Non-greasy SPF 50"}',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser",
   "Treatment": "Salicylic Acid 2% — Targets oily areas",
   "Moisturizer": "Oil-free gel moisturizer"}'),

-- Combination + Uneven Texture
('Combination', 'Uneven Texture',
 'Combination skin can have rough texture in oily areas. Gentle exfoliation and hydration smooth the skin.',
 '{"Cleanser": "Gentle foaming cleanser",
   "Treatment": "Niacinamide + Zinc serum — Smooths texture",
   "Moisturizer": "Gel moisturizer",
   "Sunscreen": "Broad-spectrum SPF 50"}',
 '{"Cleanser": "Gentle foaming cleanser",
   "Treatment": "Retinol or AHA serum — Refines skin",
   "Moisturizer": "Lightweight gel moisturizer"}'),

-- Combination + Dullness
('Combination', 'Dullness',
 'Combination skin may look lackluster due to buildup and pollution. Brightening and hydration restore glow.',
 '{"Cleanser": "CeraVe Foaming Cleanser — Removes impurities",
   "Treatment": "Vitamin C serum — Boosts radiance",
   "Moisturizer": "Lightweight gel",
   "Sunscreen": "SPF 50"}',
 '{"Cleanser": "CeraVe Foaming Cleanser",
   "Treatment": "Gentle exfoliating serum — Improves glow",
   "Moisturizer": "Lightweight gel moisturizer"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Combination + Acne
('Combination', 'Acne',
 'Combination skin can break out due to oilier zones (T-zone). Targeted routines balance oil and prevent acne.',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Controls oil without drying",
   "Treatment": "The Ordinary Niacinamide 10% + Zinc 1% — Reduces breakouts",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Non-greasy protection"}',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Removes impurities",
   "Treatment": "Paula’s Choice 2% BHA Liquid Exfoliant — Prevents clogged pores",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Hydrates dry areas"}'),

-- Combination + Pigmentation
('Combination', 'Pigmentation',
 'Combination skin may develop uneven skin tone due to sun and hormonal factors. Brightening routines restore clarity.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle cleansing",
   "Treatment": "Kiehl’s Clearly Corrective Dark Spot Solution — Reduces pigmentation",
   "Moisturizer": "Belif Moisturizing Bomb — Maintains hydration",
   "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Broad-spectrum protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "The Ordinary Alpha Arbutin 2% + HA — Target dark spots",
   "Moisturizer": "Belif Moisturizing Bomb — Locks moisture"}'),

-- Combination + Dehydration
('Combination', 'Dehydration',
 'Even combination skin can get dehydrated in drier zones. Hydrating routines restore balance.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Non-stripping",
   "Treatment": "Hyaluronic Acid Serum (The Ordinary) — Boosts hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Hydration and protection"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "Hyaluronic Acid Serum — Night hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream"}'),

-- Combination + Large Pores
('Combination', 'Large Pores',
 'Excess sebum and dead skin cause enlarged pores in combination skin. Pore-minimizing routines help refine skin texture.',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator — Controls oil",
   "Treatment": "The Ordinary Niacinamide 10% + Zinc 1% — Minimizes pores",
   "Moisturizer": "Oil-free gel moisturizer",
   "Sunscreen": "SPF 50 broad-spectrum"}',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator",
   "Treatment": "Retinol 0.2–0.5% serum — Reduces pore appearance",
   "Moisturizer": "Lightweight gel moisturizer"}'),

-- Combination + Oil Control
('Combination', 'Oil Control',
 'Combination skin requires balancing oily and dry zones. Focus on gentle oil control and hydration.',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser — Controls oil",
   "Treatment": "Niacinamide Serum — Reduces excess sebum",
   "Moisturizer": "Lightweight gel moisturizer",
   "Sunscreen": "Non-greasy SPF 50"}',
 '{"Cleanser": "La Roche-Posay Effaclar Gel Cleanser",
   "Treatment": "Salicylic Acid 2% — Targets oily areas",
   "Moisturizer": "Oil-free gel moisturizer"}'),

-- Combination + Uneven Texture
('Combination', 'Uneven Texture',
 'Combination skin can have rough texture in oily areas. Gentle exfoliation and hydration smooth the skin.',
 '{"Cleanser": "Gentle foaming cleanser",
   "Treatment": "Niacinamide + Zinc serum — Smooths texture",
   "Moisturizer": "Gel moisturizer",
   "Sunscreen": "Broad-spectrum SPF 50"}',
 '{"Cleanser": "Gentle foaming cleanser",
   "Treatment": "Retinol or AHA serum — Refines skin",
   "Moisturizer": "Lightweight gel moisturizer"}'),

-- Combination + Dullness
('Combination', 'Dullness',
 'Combination skin may look lackluster due to buildup and pollution. Brightening and hydration restore glow.',
 '{"Cleanser": "CeraVe Foaming Cleanser — Removes impurities",
   "Treatment": "Vitamin C serum — Boosts radiance",
   "Moisturizer": "Lightweight gel",
   "Sunscreen": "SPF 50"}',
 '{"Cleanser": "CeraVe Foaming Cleanser",
   "Treatment": "Gentle exfoliating serum — Improves glow",
   "Moisturizer": "Lightweight gel moisturizer"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
-- Mens + Acne & Breakouts
('Mens', 'Acne & Breakouts',
 'Men with acne-prone skin often experience breakouts due to oil and shaving irritation. Gentle cleansing and targeted treatments help.',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser — Controls oil and impurities",
   "Treatment": "Paula’s Choice 2% BHA Liquid Exfoliant — Targets breakouts",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream — Lightweight hydration",
   "Sunscreen": "EltaMD UV Clear SPF 46 — Non-greasy protection"}',
 '{"Cleanser": "CeraVe Foaming Facial Cleanser",
   "Treatment": "Azelaic Acid 10% — Reduces breakouts",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream"}'),

-- Mens + Oil Control
('Mens', 'Oil Control',
 'Men with oily skin require routines that manage excess sebum without over-drying.',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator — Reduces shine",
   "Treatment": "Niacinamide 10% serum — Controls sebum production",
   "Moisturizer": "Lightweight gel moisturizer",
   "Sunscreen": "SPF 50 non-greasy broad-spectrum"}',
 '{"Cleanser": "Kiehl’s Facial Fuel Oil Eliminator",
   "Treatment": "Salicylic Acid 2% — Prevents breakouts",
   "Moisturizer": "Lightweight gel moisturizer"}'),

-- Mens + Dehydration
('Mens', 'Dehydration',
 'Men with dehydrated skin need routines that restore moisture and protect the barrier.',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Non-stripping",
   "Treatment": "Hyaluronic Acid Serum — Replenishes moisture",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream",
   "Sunscreen": "EltaMD UV Clear SPF 46"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "Squalane Oil — Locks in hydration",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream"}'),

-- Mens + Sensitivity & Irritation
('Mens', 'Sensitivity & Irritation',
 'Men with sensitive skin can experience redness and irritation. Gentle, barrier-supporting routines are essential.',
 '{"Cleanser": "La Roche-Posay Toleriane Gentle Cleanser — Soothes skin",
   "Treatment": "Niacinamide Serum — Reduces irritation",
   "Moisturizer": "Vanicream Moisturizing Cream — Non-irritating",
   "Sunscreen": "La Roche-Posay Anthelios Mineral SPF 50"}',
 '{"Cleanser": "La Roche-Posay Toleriane Gentle Cleanser",
   "Treatment": "Squalane Oil — Night hydration",
   "Moisturizer": "Vanicream Moisturizing Cream"}'),

-- Mens + Aging & Dullness
('Mens', 'Aging & Dullness',
 'Men concerned with aging and dullness benefit from antioxidant-rich routines and gentle exfoliation.',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "Vitamin C Serum — Brightens and reduces fine lines",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream",
   "Sunscreen": "EltaMD UV Clear SPF 46"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser",
   "Treatment": "Retinol 0.2–0.5% serum — Night anti-aging",
   "Moisturizer": "Neutrogena Hydro Boost Gel-Cream"}')
;
""")

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine) VALUES
('Aging', 'Fine Lines & Wrinkles', 
 'Aging skin shows fine lines and wrinkles. A routine with gentle exfoliation, hydration, and anti-aging ingredients is essential.', 
 '{"Cleanser": "CeraVe Hydrating Cleanser — Gentle cleansing without stripping", "Treatment": "The Ordinary Retinol 0.5% — Reduces fine lines", "Moisturizer": "Neutrogena Hydro Boost Water Gel — Hydrates and plumps", "Sunscreen": "La Roche-Posay Anthelios SPF 50 — Protects from UV damage"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser — Removes impurities without drying", "Treatment": "Paula’s Choice 1% Retinol — Supports cell turnover", "Moisturizer": "Neutrogena Hydro Boost Water Gel — Locks in moisture"}'),

('Aging', 'Loss of Elasticity',
 'Aging skin loses firmness and elasticity. Ingredients that boost collagen and hydrate deeply help maintain skin resilience.',
 '{"Cleanser": "Gentle foaming cleanser — Prepares skin for active ingredients", "Treatment": "Vitamin C serum — Stimulates collagen and brightens", "Moisturizer": "Rich moisturizer with peptides — Supports skin structure", "Sunscreen": "Broad-spectrum SPF 50"}',
 '{"Cleanser": "Gentle foaming cleanser", "Treatment": "Peptide serum — Enhances elasticity", "Moisturizer": "Rich moisturizer — Hydrates and firms"}'),

('Aging', 'Dryness & Dehydration',
 'Aging skin is prone to dryness. A routine focused on intense hydration and barrier repair is key.',
 '{"Cleanser": "CeraVe Hydrating Cleanser", "Treatment": "Hyaluronic Acid serum — Deep hydration", "Moisturizer": "Thick cream moisturizer — Locks in moisture", "Sunscreen": "SPF 50 broad-spectrum"}',
 '{"Cleanser": "CeraVe Hydrating Cleanser", "Treatment": "Hyaluronic Acid serum", "Moisturizer": "Thick cream moisturizer"}'),

('Aging', 'Dullness',
 'Aging skin can look lackluster. Brightening and gentle exfoliation improve radiance.',
 '{"Cleanser": "Brightening gel cleanser — Removes impurities", "Treatment": "Vitamin C serum — Enhances glow", "Moisturizer": "Lightweight hydrating gel", "Sunscreen": "SPF 50"}',
 '{"Cleanser": "Brightening gel cleanser", "Treatment": "AHA serum — Promotes cell turnover", "Moisturizer": "Hydrating gel"}'),

('Aging', 'Pigmentation',
 'Aging skin may develop pigmentation spots. Ingredients that brighten and protect are important.',
 '{"Cleanser": "CeraVe Foaming Cleanser", "Treatment": "Niacinamide 10% serum — Reduces pigmentation", "Moisturizer": "Light gel moisturizer", "Sunscreen": "SPF 50 broad-spectrum"}',
 '{"Cleanser": "CeraVe Foaming Cleanser", "Treatment": "AHA or gentle exfoliant", "Moisturizer": "Light gel moisturizer"}');
""")'''

mycursor.execute("""
INSERT INTO SkinInfo (skin_type, concern, description, am_routine, pm_routine)
VALUES
(
  'Sensitive',
  'Redness',
  'Sensitive skin with redness needs calming and soothing ingredients to reduce inflammation.',
  '{"Cleanser": "La Roche-Posay Toleriane Hydrating Gentle Cleanser", "Treatment": "Avene Antirougeurs Soothing Serum", "Moisturizer": "CeraVe Moisturizing Cream", "Sunscreen": "EltaMD UV Clear SPF 46"}',
  '{"Cleanser": "La Roche-Posay Toleriane Hydrating Gentle Cleanser", "Treatment": "Azelaic Acid 10% — Reduces redness and irritation", "Moisturizer": "CeraVe PM Facial Moisturizing Lotion"}'
),
(
  'Sensitive',
  'Sensitivity',
  'Sensitive skin requires gentle, fragrance-free products that strengthen the skin barrier.',
  '{"Cleanser": "Vanicream Gentle Facial Cleanser", "Treatment": "La Roche-Posay Cicaplast Baume B5", "Moisturizer": "Bioderma Sensibio Light Cream", "Sunscreen": "ISDIN Eryfotona Actinica SPF 50"}',
  '{"Cleanser": "Vanicream Gentle Facial Cleanser", "Treatment": "Niacinamide 5% Serum — Calms sensitivity", "Moisturizer": "Bioderma Sensibio Light Cream"}'
),
(
  'Sensitive',
  'Barrier Repair',
  'When the skin barrier is damaged, focus on ceramides and hydrating, soothing products.',
  '{"Cleanser": "CeraVe Hydrating Cleanser", "Treatment": "Paula’s Choice Omega+ Complex Serum", "Moisturizer": "CeraVe Moisturizing Cream", "Sunscreen": "Eucerin Sensitive Mineral SPF 50"}',
  '{"Cleanser": "CeraVe Hydrating Cleanser", "Treatment": "La Roche-Posay Cicaplast Baume B5", "Moisturizer": "CeraVe Moisturizing Cream"}'
),
(
  'Sensitive',
  'Dehydration',
  'Dehydrated sensitive skin needs gentle hydration boosters like hyaluronic acid and soothing agents.',
  '{"Cleanser": "Simple Micellar Gel Wash", "Treatment": "The Ordinary Hyaluronic Acid 2% + B5", "Moisturizer": "Clinique Moisture Surge", "Sunscreen": "Avene Very High Protection SPF 50+"}',
  '{"Cleanser": "Simple Micellar Gel Wash", "Treatment": "La Roche-Posay Hyalu B5 Serum", "Moisturizer": "Clinique Moisture Surge"}'
),
(
  'Sensitive',
  'Acne',
  'Sensitive skin with acne needs a careful balance of soothing and mild anti-acne treatments.',
  '{"Cleanser": "Avene Cleanance Cleansing Gel", "Treatment": "La Roche-Posay Effaclar Duo", "Moisturizer": "Cetaphil PRO Oil Absorbing Moisturizer", "Sunscreen": "EltaMD UV Clear SPF 46"}',
  '{"Cleanser": "Avene Cleanance Cleansing Gel", "Treatment": "Differin (Adapalene) Gel 0.1%", "Moisturizer": "Cetaphil PRO Oil Absorbing Moisturizer"}'
)
""")


db.commit()